export const STRIPE_PLANS = {
  free: {
    name: 'Free',
    price: 0,
    priceId: 'price_1SLO7pAtySMHx8WMro7nxmTJ',
    interval: 'one-time',
    features: [
      '1 Integration',
      '1 Workspace',
      'Unlimited Users',
      'Email notifications',
      'Hourly alerts',
      'Historical backfill',
      'Unlimited data retention',
    ],
  },
  starter_monthly: {
    name: 'Starter',
    price: 29,
    priceId: 'price_1SLNwlAtySMHx8WMPkQ97Dwt',
    interval: 'month',
    features: [
      '3 Integrations',
      '3 Workspaces',
      'Unlimited Users',
      'Email notifications',
      'Slack notifications',
      'Web push notifications',
      'Hourly alerts',
      'Historical backfill',
      'Unlimited data retention',
    ],
  },
  starter_yearly: {
    name: 'Starter',
    price: 199,
    priceId: 'price_1SLNwlAtySMHx8WM8OcSHwan',
    interval: 'year',
    features: [
      '3 Integrations',
      '3 Workspaces',
      'Unlimited Users',
      'Email notifications',
      'Slack notifications',
      'Web push notifications',
      'Hourly alerts',
      'Historical backfill',
      'Unlimited data retention',
    ],
  },
  pro_monthly: {
    name: 'Pro',
    price: 99,
    priceId: 'price_1SLO8cAtySMHx8WMhGYEGt2M',
    interval: 'month',
    features: [
      '10 Integrations',
      '10 Workspaces',
      'Unlimited Users',
      'Email notifications',
      'Slack notifications',
      'Web push notifications',
      'Hourly alerts',
      'Historical backfill',
      'Unlimited data retention',
    ],
  },
  pro_yearly: {
    name: 'Pro',
    price: 799,
    priceId: 'price_1SLO8xAtySMHx8WM7JkY1m2W',
    interval: 'year',
    features: [
      '10 Integrations',
      '10 Workspaces',
      'Unlimited Users',
      'Email notifications',
      'Slack notifications',
      'Web push notifications',
      'Hourly alerts',
      'Historical backfill',
      'Unlimited data retention',
    ],
  },
} as const;

export type PlanKey = keyof typeof STRIPE_PLANS;
